### ISSUE TITLE
Error while installing vlc-python

### ISSUE THREAD

**Issue by sagarrakshe** [geoffsalmon/vlc-python#2]
I got the following error when executed the **setup.py** file.

```
Traceback (most recent call last):
File "setup.py", line 9, in <module>
raise Exception("This script should be run from a VLC tree.")
Exception: This script should be run from a VLC tree.
```

What does it mean?

**Comment by geoffsalmon** [comment]
The vlc.py module is generated by parsing the C header files of vlc. To successfully run setup.py and generate vlc.py you need to place the vlc-python repo inside the vlc repo so that the relative path "../../include/vlc" points to vlc's headers.

However, unless you have modified either vlc or the vlc-python wrapper, you can use the already generated file which generated/vlc.py. There's no need to run setup.py or generate your own. Copy generated/vlc.py to your project and import it.

I'd urge you to use the official vlc-python code at http://git.videolan.org/?p=vlc/bindings/python.git instead of mine. Mine is out of date.

**Comment by shamun** [comment]
To make this simple for visitors, so that you can start quickly here is the follow up:

Step 1:

`cd /var/tmp
git://git.videolan.org/vlc/bindings/python.git
cd python
cp ../examples/gtkvlc.py ./`

Step 2: play

`python gtkvlc.py`
